[package]
name = "rayrs"
version = "0.1.0"
authors = ["Hampus Fröjdholm <hampus.frojdholm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayrs-lib = {path = "../rayrs-lib"}
rayon = "1.3"
image = "0.23"
